### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by thaume** [emberjs-paris/website#1]
Hey @tchak ! 

Mise à jour pour le kiff ou perspective pour la rentrée ? :) 

Dès que tu es chaud j'ai plusieurs personnes qui seraient prête à s'investir sur un nouveau meetup Ember.

J'espère que tu vas bien !

**Comment by tchak** [comment]
Right now - playing around with PWA :) But definitely would love for something to happen soon. I will be back in Paris first week of September. Let's talk then.
